### ISSUE TITLE
Printing stats during runtime destruction can lead to weird bugs

### ISSUE THREAD

**Issue by sebastiankreutzer** [tudasc/TypeART#50]
Currently, the collected stats are serialized and printed when the programs exits, during the destruction of the runtime global.
However, when `RuntimeSystem::~RuntimeSystem` is called,  the LLVM streams `llvm::outs()/errs()` have already been destroyed.
The logging system depends on these functions. If it is used at this point, the program crashes.

This can lead to problems in certain scenarios. For example, consider the `24_threads_type_check.cpp` test.
Both the `AccessRecorder` and the test itself use atomics. Consequently, some of the functions implemented in the `<atomic>` are instrumented, if not filtered out.
During the serialization of the softcounters, one of these instrumented functions is called, which causes `__typeart_on_alloc_stack` to be invoked.
This in turn prompts an entry into the log, crashing the program.

For now, I'm adding a check that will stop the callback functions from being triggered from within the runtime's destructor.
In the future, we might want to think about avoiding this issue altogether, by printing the softcounter stats at an earlier time.
I can think of two possible options:
1. Add an API call, such as `typeart_finalize`, which the application has to call explicitly.
2. Automatically insert this call at the end of `main` (of course this will no work if the program returns via `exit(0)` or similar).  

We may also choose to leave the code as is and be mindful of potential future issues.

**Comment by ahueck** [comment]
I think the proposed disabling of the callback functions at destruction time of the runtime is a sensible solution for now.

**Comment by sebastiankreutzer** [comment]
Tacking calls from within the runtime constructor/destructor is now prevented.
I'm leaving this issue open because the problem with `llvm::outs()` remains.
