### ISSUE TITLE
error: no member named '_Link_type' in std::map<K,V>::iterator

### ISSUE THREAD

**Issue by jprotze** [tudasc/TypeART#58]
Compiling TypeART against libc++ fails. Is _Link_type libstdc++ specific?

**Comment by ahueck** [comment]
Yes, this is indeed a libstdc++ specific construct in `stl_tree.h`.
It is used for calculating the size of a node in the std::map impl. for our datatypes, see https://github.com/tudasc/TypeART/blob/e8655c3d1b72404387935e4d23295914f07699ce/lib/runtime/AccessCountPrinter.h#L25

It makes sense to replace that with a stl-independent estimate.

**Comment by jprotze** [comment]
Is this for (optional) statistics or crucial for the functionality?

**Comment by ahueck** [comment]
Entirely optional. Just to see a very rough (max) memory usage estimate of the runtime data structures.
